CREATE SEQUENCE STUDENT_ID_SEQ
START WITH 1
INCREMENT BY 1


CREATE SEQUENCE TEACH_ID_SEQ
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE CS_ID_SEQ
START WITH 1 
INCREMENT BY 1;

SELECT * FROM ENROLLMENT;
CREATE SEQUENCE ENROLLMENT_ID_SEQ
START WITH 1
INCREMENT BY 1;