CREATE TABLE CLASSROOM(
    CLASSROOM_ID    NUMBER  PRIMARY KEY,
    ROOM_NUMBER     VARCHAR2(20),
    CAPACITY        NUMBER,
    LOCATION        VARCHAR2(100)
);

CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID   NUMBER  PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(100)
);

CREATE TABLE PROFESSOR(
    PROFESSOR_ID    NUMBER  PRIMARY KEY,
    PROFESSOR_NAME  VARCHAR2(100),
    BIRTH_DATE      DATE,
    EMAIL           VARCHAR2(100),
    HIRE_DATE       DATE,
    PHONE_NUMBER    NUMBER,
    DEPARTMENT_ID   NUMBER  REFERENCES  DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE STUDENT(
    STUDENT_ID      NUMBER  PRIMARY KEY,
    STUDENT_NAME    VARCHAR2(100),
    EMAIL           VARCHAR2(100),
    BIRTH_DATE      DATE,
    CGPA            NUMBER(3,2),
    CREDIT_HOURS    NUMBER,
    DEPARTMENT_ID   NUMBER  REFERENCES  DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE COURSE(
    COURSE_ID       NUMBER  PRIMARY KEY,
    COURSE_NAME     VARCHAR(100),
    CREDIT_HOURS    NUMBER,
    DEPARTMENT_ID   NUMBER  REFERENCES  DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE ENROLLMENT(
    ENROLLMENT_ID   NUMBER  PRIMARY KEY,
    START_DATE      DATE,
    END_DATE        DATE,
    GRADE           VARCHAR2(2),
    STUDENT_ID      NUMBER  REFERENCES  STUDENT(STUDENT_ID),
    COURSE_ID       NUMBER  REFERENCES  COURSE(COURSE_ID)
);

CREATE TABLE TEACH(
    TEACH_ID        NUMBER  PRIMARY KEY,
    SEMESTER        VARCHAR2(20),
    YEAR            NUMBER(4),
    PROFESSOR_ID    NUMBER  REFERENCES  PROFESSOR(PROFESSOR_ID),
    COURSE_ID       NUMBER  REFERENCES  COURSE(COURSE_ID) 
);

CREATE TABLE COURSE_SCHEDULE(
    CS_ID           NUMBER  PRIMARY KEY,
    DAYOFWEEK       VARCHAR2(20),
    START_TIME      TIMESTAMP,
    END_TIME        TIMESTAMP,
    COURSE_ID       NUMBER  REFERENCES  COURSE(COURSE_ID),
    CLASSROOM_ID    NUMBER  REFERENCES  CLASSROOM(CLASSROOM_ID)
);
